name: 9c93763a-bef9-4b17-be5d-9888009fa74f

on:
  schedule:
    - cron: "0 0 * * *"   # UTC
  workflow_dispatch:       # Allow manual trigger from UI

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      start_ts: ${{ steps.ts.outputs.start_ts }}

    steps:
      - id: ts
        shell: bash
        run: echo "start_ts=$(date +%s%3N)" >> "$GITHUB_OUTPUT"

  _1:
    needs:
      - init
    runs-on: ubuntu-latest

    steps:
      - &checkout_manage_repo
        name: Checkout _manage repository
        uses: actions/checkout@v6
        with:
          repository: phan2410/_manage
          token: ${{ secrets._2_1 }}

      - name: Main
        working-directory: ./github/${{ github.workflow }}
        env:
          GH_WORKFLOW_START_TS: ${{ needs.init.outputs.start_ts }}
          _l_0: ${{ secrets._l_0 }}
          _1_1: ${{ secrets._1_1 }}
        run: ./${{ github.job }}.sh
  _2:
    needs:
      - init
      - _1
    runs-on: ubuntu-latest

    steps:
      - *checkout_manage_repo
      - name: Main
        working-directory: ./github/${{ github.workflow }}
        env:
          GH_WORKFLOW_START_TS: ${{ needs.init.outputs.start_ts }}
          _l_0: ${{ secrets._l_0 }}
          _2_1: ${{ secrets._2_1 }}
          _2_2: ${{ secrets._2_2 }}
          _2_3: ${{ secrets._2_3 }}
        run: ./${{ github.job }}.sh